"""add updated_at to users

Revision ID: 48acbd777954
Revises: ff7a256c3f66
Create Date: 2026-04-20 20:03:58.641571

"""

from collections.abc import Sequence
from datetime import datetime, timezone

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48acbd777954"
down_revision: str | Sequence[str] | None = "ff7a256c3f66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the column allowing NULL temporarily
    op.add_column("users", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    # Step 2: Fill existing rows with the current timestamp
    op.execute(f"UPDATE users SET updated_at = '{datetime.now(timezone.utc).isoformat()}'")
    # Step 3: Now that all rows have a value, set NOT NULL
    op.alter_column("users", "updated_at", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    # ### end Alembic commands ###
